version: '3'

services:
  minio:
    image: docker.io/bitnami/minio:2025
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minio-user
      - MINIO_ROOT_PASSWORD=P@ssw0rd!
      - MINIO_DEFAULT_BUCKETS=test

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local